/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d7",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#007f36",
        "on-primary": "#ffffff",
        "tertiary": "#006329",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "outline": "#737686",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#3c475a",
        "error-container": "#ffdad6",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "secondary": "#545f73",
        "on-tertiary-fixed-variant": "#005320",
        "primary-container": "#2563eb",
        "surface-tint": "#0053db",
        "background": "#f8f9ff",
        "on-tertiary-container": "#c7ffca",
        "on-surface": "#0b1c30",
        "secondary-container": "#d5e0f8",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#7ffc97",
        "on-primary-container": "#eeefff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00174b",
        "on-secondary-container": "#586377",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002109",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-secondary-fixed": "#111c2d",
        "secondary-fixed": "#d8e3fb",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#434655",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#62df7d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#bcc7de",
        "on-tertiary": "#ffffff",
        "primary": "#004ac6",
        "inverse-primary": "#b4c5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "gutter": "1rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-desktop": "2rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "title-md": ["Inter"],
        "currency-display": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "title-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "title-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "currency-display": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}